# Generated by Django 2.0.2 on 2018-02-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('catalog', '0003_auto_20180219_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='attribute',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='attribute',
            table=None,
        ),
        migrations.AlterModelTable(
            name='brand',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='feature',
            table=None,
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productdata',
            table=None,
        ),
    ]
