# Generated by Django 2.0.2 on 2018-04-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_platform_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teachers', to='edu_platform_app.Course'),
        ),
    ]
