# Generated by Django 2.0.2 on 2018-04-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_platform_app', '0002_auto_20180408_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='wave',
            new_name='group',
        ),
    ]
