# Generated by Django 2.0.2 on 2018-04-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_platform_app', '0003_auto_20180408_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(default='zzz', max_length=100),
        ),
    ]
