# Generated by Django 2.0.2 on 2018-04-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_platform_app', '0004_course_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
